export const action = {
  connectionGet: "connection.get",
  connectionSave: "connection.save",
  connectionDisconnect: "connection.disconnect",
  oauthStart: "oauth.start",
  repositoriesList: "repositories.list",
  repositoriesBranches: "repositories.branches",
  repositoriesInspect: "repositories.inspect",
  pullRequestsGet: "pullrequests.get",
  pullRequestsAssociations: "pullrequests.associations",
  pullRequestsInspect: "pullrequests.inspect",
  pullRequestsLink: "pullrequests.link",
  pullRequestsCreate: "pullrequests.create",
  pullRequestsUnlink: "pullrequests.unlink",
  reviewsAction: "reviews.action",
  tasksLaunch: "tasks.launch",
  watchesGet: "watches.get",
  watchesUpdate: "watches.update",
  watchesRun: "watches.run",
  watchesPause: "watches.pause",
  watchesResume: "watches.resume",
  watchesPreviewReset: "watches.preview_reset",
  watchesPreviewDelete: "watches.preview_delete",
  watchesReset: "watches.reset",
  watchesDelete: "watches.delete",
} as const;
